# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_email_test.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_email_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemail',
            name='bcc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testemail',
            name='body',
            field=models.TextField(default="Here's some default text."),
        ),
        migrations.AlterField(
            model_name='testemail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The date you want to set as the date header.'),
        ),
        migrations.AlterField(
            model_name='testemail',
            name='error',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='testemail',
            name='from_email',
            field=models.CharField(default=django_email_test.models.test_email_default_from_email, max_length=150, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='testemail',
            name='subject',
            field=models.CharField(default='This is a test email.', max_length=150),
        ),
        migrations.AlterField(
            model_name='testemail',
            name='to',
            field=models.TextField(blank=True, default=''),
        ),
    ]
